### ISSUE TITLE
About setting up

### ISSUE THREAD

**Issue by t-cool** [jscl-project/closette-jscl#1]
@vlad-km 
Hi.
Could you tell me how to set up closette on JSCL?
I'd like to try it before merging it into JSCL.
I'd appreciate your help.

**Comment by vlad-km** [comment]
@t-cool 
Hi.
I compiled the system in the Moren. SDF file for compilation, in the same repository. 
As far as I can remember, the Moren environment you installed.

Another way, this is a host compilation. I did not pass it yet. I can not comment on anything.

And the third way. A little later, I'll upload  in the repository js bandle.  You can use it.

About integration with JSCL. I can only say, in this form, CLOSETTE can not be integrated. Are needed a complete redesign and optimization.

Thanks

**Comment by t-cool** [comment]
Thank you for your reply!
I'll try it on Moren!
